#28: non-zero exit codes for 'list' and 'search' not found: initial commit
makedeb/mist pull request #29
Opened 2022-10-02 18:06 UTC by tonky

Hey Hunter, saw you post on `mist` in `/r/linux` yesterday!

As a fan of Arch/AUR(though using PopOS atm) i gave it a try and installed `nodejs` and `npm` from `MPR` - good stuff, i'd say!

Then i checked out the `mist` repo - and bam, it's in rust!

Well, i have some time on my hands and some rust experience, so why not contribute to a good project?!

Here's the initial draft of #28.

Given that there are a lot of hidden assumptions here(expected test structure? `exitcode::USAGE` for missing 'package base'? rest of subcommands?), i'd like to have some input from you on structure/tests/overall picture.

Feel free to comment on PR, so it can be improved as you see fit.

2022-10-02 18:47 UTC, hwittenborn commented
Hey, thanks for the kind words :) thanks for the MR too, it's always great to get some contributors in here!

I'm out right now, but I'll be home in a few hours and then I can get this looked over

2022-10-03 05:58 UTC, hwittenborn requested changes
Hey! Sorry for the delay, I crashed right after I got home earlier and just now woke up :p

2022-10-03 05:58 UTC, hwittenborn commented on src/clone.rs
> +        return exitcode::USAGE;
Could we keep the `quit::with_code` stuff in the codebase?  It's also used in places like https://github.com/makedeb/mist/blob/d9f88b80a9f48283642473051a078395cb44da81/src/install_util.rs#L46 which I don't believe got removed, and having them in allows the codebase to not have a lot of nested checks for when to exit

2022-10-03 05:58 UTC, hwittenborn commented on src/clone.rs
>  }
I feel like this would be better as a test run from the build executable like running `mist clone nonexistent` or something, especially considering the previous comment about `quit::with_code` usage. [Just](https://github.com/casey/just) was being used a while back for tests, and we could probably just throw some test commands into there if you'd want. makedeb itself also uses [bats](https://github.com/bats-core/bats-core) for tests, and I think it could be good to throw that in here for the tests if you think it would be appropriate.

All that could be done in the future if you don't want that tacked in the MR though. Some more thorough testing probably does need to be done at some point though, especially for things in `src/util.rs`, as I imagine those wouldn't be too hard to implement tests for. Again though, that can all be figured out sometime in the future if you don't want that done in this MR.

2022-10-03 18:03 UTC, hwittenborn requested changes

2022-10-04 16:32 UTC, tonky commented on .justfile
> +    if ./target/debug/mist list nonexistent; then echo "Missing 'list' results should not exit with status code 0" && exit 1; fi
toast is interesting ,haven't seen one before.

okay, i've added a sample 'toastfile', but it looks like test is hanging on `list` or `search` invocation after `mist update` in container. maybe you have an idea about why it does.

and i can't make `act` to run `test` GHA `pr.jobs.test` locally - it errors out with `/bin/sh: 1: curl: not found`.
although the GHA code is just straight from [toast readme](https://github.com/stepchowfun/toast#running-toast-in-ci).

so, um, it looks like i've created more problem then sovled :-D

2022-10-07 18:12 UTC, hwittenborn requested changes

2022-10-07 18:12 UTC, hwittenborn commented on .justfile
> +    if ./target/debug/mist list nonexistent; then echo "Missing 'list' results should not exit with status code 0" && exit 1; fi
> it looks like test is hanging on `list` or `search` invocation after `mist update` in container.

I just remembered that being an issue with Mist, I'm not sure what's causing it. I opened up #31 a bit ago to track the issue though, but I haven't looked into it too much if I'm being honest.

> and i can't make `act` to run `test` GHA pr.jobs.test locally

What's `act`? Sorry if I'm just overlooking something :p

2022-10-07 18:13 UTC, hwittenborn commented
Sorry for the delayed comments on all that, looks like I forgot to submit my review and they all remained in a pending state on GitHub :p

2022-10-08 09:02 UTC, tonky commented on .justfile
> +    if ./target/debug/mist list nonexistent; then echo "Missing 'list' results should not exit with status code 0" && exit 1; fi
[act](https://github.com/nektos/act) is a local executor of GHA tasks, to test them locally.

2022-10-08 10:43 UTC, tonky commented on .github/workflows/pr.yml
> +      - uses: stepchowfun/toast/.github/actions/toast@main
I've checked the `makedeb` repo, and it's not using `toast` in pipelines, so i'm not sure of another good way(besides recommended one) to incorporate it into  this GHA. I mean - i can't really run `toast` from the `pr.yml`, because there's no automatic DIND binding when running `toast`:

```
# py.yml
[skipped...]
  test2:
    runs-on: ubuntu-latest
    container:
      image: proget.hunterwittenborn.com/docker/makedeb/makedeb-alpha:ubuntu-focal
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
      - name: Run integration tests
        run: |
          curl -q 'https://proget.makedeb.org/debian-feeds/prebuilt-mpr.pub' | gpg --dearmor | sudo tee /usr/share/keyrings/prebuilt-mpr-archive-keyring.gpg 1> /dev/null
          echo "deb [signed-by=/usr/share/keyrings/prebuilt-mpr-archive-keyring.gpg] https://proget.makedeb.org prebuilt-mpr $(lsb_release -cs)" | sudo tee /etc/apt/sources.list.d/prebuilt-mpr.list
          sudo apt update
          sudo apt install toast -y
          toast```

leads to this: 
```
act -j test2
[.skipped..]
[ERROR] Unable to pull image.
| Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=proget.hunterwittenborn.com%2Fdocker%2Fmakedeb%2Fmakedeb-alpha&tag=ubuntu-focal": dial unix /var/run/docker.sock: connect: permission denied
```

Here's how i checked if `toast` is used in `makedeb` -  can find it only in `readme`, not in pipelines:

```
❯ (makedeb) rg -. toast
CONTRIBUTING.md
65:To run unit tests, you'll need [Toast](https://github.com/stepchowfun/toast) installed.
68:[Toast is available on the MPR](https://mpr.makedeb.org/packages/toast) if you want to install Toast with makedeb. You'll likely also need the latest version of the Rust compiler toolchain, which is [also available on the MPR](https://mpr.makedeb.org/packages/rustc).
78:git clone 'https://mpr.makedeb.org/toast'
79:cd toast/
87:sudo apt install toast
```

2022-10-10 21:05 UTC, hwittenborn commented on .github/workflows/pr.yml
> +      - uses: stepchowfun/toast/.github/actions/toast@main
> Here's how i checked if toast is used in makedeb - can find it only in readme, not in pipelines

It's in `.drone/scripts/install-deps.sh`, I'm about to push some changes that should fix this issue though

2022-10-10 21:05 UTC, hwittenborn commented on .justfile
> +    if ./target/debug/mist list nonexistent; then echo "Missing 'list' results should not exit with status code 0" && exit 1; fi
Just got a chance to look into act, I don't know much about `act` but I'm pretty sure most of those Docker issues are due to act running all builds in Docker, which means things like Toast which also use Docker can't run because docker-in-docker isn't set up. That's just my best guess though, I wouldn't know much honestly, but I'm about to push changes to at least make it work on the GitHub Actions side, I'm not quite sure they'll work locally yet still.

2022-10-10 21:20 UTC, hwittenborn commented
I just pushed some changes to remove that hanging issue you experienced, I also added a Justfile so the `sudo chown` and `sudo chmod` stuff doesn't have to be repeated everywhere. I'm probably gonna want to set up some stuff with `bats` after this for the end-to-end tests - do you want to tackle those or do you want me to get those done?

Let me know if you're having any trouble with my changes either, I'll be available to help

2022-10-10 22:59 UTC, hwittenborn commented
Sorry for all these dummy commits, I can't do much local testing atm - I'm just doing one last test and then this should all be ready to merge though - lmk if you have any questions or comments about anything, I'll get it merged after that.

2022-10-31 13:39 UTC, hwittenborn commented
I'm gonna go ahead and get this merged @tonky, we can get things changed still as you need though, just let me know.

Thanks a ton for the contribution! :)

2022-10-31 13:40 UTC, merged

2022-11-02 06:45 UTC, tonky commented
Thanks for seeing this though, Hunter!
Sorry fo my disappearance, some real life stuff got in the way :)

2022-11-02 18:06 UTC, hwittenborn commented
Not a problem, there isn't too much of a rush for any of this. Thanks for letting me know though!